Interactivity Update
hacksu/hacksu-website pull request #33
Opened 2023-10-18 03:44 UTC by toBeOfUse

This adds a "login" button to the top right of the screen. Logins work through Discord. Logins succeed if you have the "Leader" role in the HacKSU server. Once logged in, you can access the "admin" page and edit redirect links, the staff page, and the events page. The look of the "events" (meetings) page is not finalized; I want to make it scroll down to the next upcoming event, and maybe put that event on the home page as well. Also, we could consider adding images (such as Instagram embeds) to events.

2023-10-18 15:14 UTC, cseitz requested changes
I like the approach to having some edit pages to avoid needing to deploy the website just for basic content changes! I left some feedback since I saw a few things that sticked out to me.

2023-10-18 15:14 UTC, cseitz commented on example.server.config.json
It might also be worthwhile to look into defining these as [GitHub environment variables](https://docs.github.com/en/actions/learn-github-actions/variables) in the project and adjusting the CI pipeline to automatically deploy those variables. Currently you have to SSH into the server to update the config, which is pretty annoying tbh.

We could dump the pipeline env into a file and upload that during deployment.

Take a look at this for a really nice environment validation lib: https://env.t3.gg/docs/introduction

2023-10-18 15:14 UTC, cseitz commented on src/components/HotCard.vue
Looks like the Navigation bar is being shown on this page. Would recommend implementing a fix to hide it here.

I assume you know, but this is the page I made to create those hotcard things. You can edit this page and follow its instructions and you can send the PDF to the FedEx store near the architecture building and they can print out a bunch of physical cards for us.

I think I chose the matte finish?

2023-10-18 15:14 UTC, cseitz commented on src/router/index.js
> +    path: "/edit-staff",
Super minor, but personally I'd recommend `/admin/staff` and `/admin/events` since they're both part of the `/admin` interface.

2023-11-05 05:02 UTC, toBeOfUse commented on src/components/Navigation.vue
> +          ['Leadership', '/leadership'],
"Leadership" definitely sounds more important than "Staff," so that's a plus

2024-01-04 23:23 UTC, merged